### ISSUE TITLE
Update examples/README.md

### ISSUE THREAD

**Issue by SynSnipe** [WM-SEMERU/ACER#1]
It appears `python >= 3.10.x` is required versus the suggestion in the README which states `python >=3.8.10`.  
The Match-Case Statement does not exist until Python 3.10.  My first attempt was with `python ==3.9.6` which was unsuccessful due to the match keyword not existing causing a syntax error, seen in the attached screenshot.

Obviously not critical but for sake of accuracy.
![image](https://github.com/WM-SEMERU/ACER/assets/3219561/df0a87ab-1b4a-4e44-8dfa-bbb9f9560fb1)

**Comment by BlastWind** [comment]
Thanks for catching this, Sean!
